services:
  redis-sample-api:
    image: ${DOCKER_REGISTRY-}redis-sample-api
    build:
      context: .
      dockerfile: docker-redis-sample/Dockerfile
    ports:
      - "5000:443"
    depends_on:
      - redis-search-composed-container
  redis-search-composed-container:
   image: redislabs/redisearch:latest
   ports:
      - "6379:6379"